server:
  port: 8088


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: admin-server

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
