server:
  port: 8081


spring:
  application:
    name: admin-client

---
#spring.boot.admin.client.url: "http://localhost:8088"
management.endpoints.web.exposure.include: "*"
---
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      defaults:
        enabled: true
    heapdump:
      show-details: always

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
spring:
  boot:
    admin:
      client:
        instance:
          name: admin-client
        url: "http://localhost:8088/"